# Generated by Django 6.0.1 on 2026-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_fashionitem_fashionvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionvariant',
            name='size',
            field=models.CharField(choices=[('A', 'All'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5),
        ),
    ]
