# Generated by Django 6.0.1 on 2026-01-30 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='fashion_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.fashionitem'),
        ),
    ]
