# Generated by Django 6.0.1 on 2026-02-10 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MobileSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('browse_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sim_type', models.CharField(blank=True, max_length=100, null=True)),
                ('touchscreen', models.BooleanField(default=True)),
                ('otg_compatible', models.BooleanField(default=False)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpu', models.CharField(blank=True, max_length=100, null=True)),
                ('display_type', models.CharField(blank=True, max_length=100, null=True)),
                ('other_display_features', models.TextField(blank=True, null=True)),
                ('os', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('processor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('processor_core', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_frequency', models.TextField(blank=True, null=True)),
                ('internal_storage', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_camera', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_camera_features', models.TextField(blank=True, null=True)),
                ('secondary_camera', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_camera_features', models.TextField(blank=True, null=True)),
                ('video_recording_resolution', models.TextField(blank=True, null=True)),
                ('digital_zoom', models.CharField(blank=True, max_length=50, null=True)),
                ('network_type', models.CharField(blank=True, max_length=100, null=True)),
                ('supported_networks', models.TextField(blank=True, null=True)),
                ('bluetooth_version', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi_version', models.CharField(blank=True, max_length=100, null=True)),
                ('nfc', models.BooleanField(default=False)),
                ('gps_support', models.BooleanField(default=True)),
                ('sensors', models.TextField(blank=True, null=True)),
                ('battery_type', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=50, null=True)),
                ('height', models.CharField(blank=True, max_length=50, null=True)),
                ('depth', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='blog.product')),
            ],
        ),
    ]
