# Generated by Django 6.0.1 on 2026-02-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.DeleteModel(
            name='MobileSpecification',
        ),
    ]
