# Generated by Django 6.0.1 on 2026-02-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_flight_arrival_time_alter_flight_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fashionvariant',
            name='size',
            field=models.CharField(choices=[('All', 'All'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], max_length=5),
        ),
    ]
